
version: 2

models:
  - name: stg_beers
    description: Table containing the realised revenue
    columns:
      - name: beer
        description: The name of the beer
        tests:
          - not_null
          - unique
