
version: 2

models:
  - name: stg_beers
    description: Table containing the realised revenue
    columns:
      - name: beer
        description: The name of the beer
        tests:
          - not_null
          - unique
      - name: style
      - name: brewery
      - name: city
      - name: state
        tests:
          - accepted_values:
              values: ["AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MO", "MS", "MT","NC","ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY"]
      - name: ibu
      - name: abv
